### PR TITLE
Fix required string in nodemanager start template

### PR DESCRIPTION
**Pull request by hajee**

### CODE REVIEW

**Comment by biemond** [comment]
Maybe otherway around if version is 1036 or 1211

**Comment by hajee** [comment]
I thought that the 12 versions have a nodemanager per domain and 10.3 has a node manager per node. I think this code does that?

**Comment by biemond** [comment]
What I mean , nodemanager a domain it is the new standard. You are now missing 12.2.1 and future versions

**Comment by hajee** [comment]
Ah. I see. I will change it

**Pull request merged**
